extensions:
  health_check:
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  zipkin:
  hostmetrics:
    scrapers:
      load:
      cpu:
      disk:
      filesystem:
      memory:
      network:
      paging:
      process:

processors:
  batch:
    timeout: 10s

exporters:
  logging:
    # logLevel: debug
  file/traces:
    path: /log/otel/traces.log
  file/metrics:
    path: /log/otel/metrics.log
  file/logs:
    path: /log/otel/logs.log
  otlp:
    endpoint: "${JAEGER_ENDPOINT}"
    tls:
      insecure: true
  prometheus:
    endpoint: "${PROMETHEUS_ENDPOINT}"
  loki:
    endpoint: "${LOKI_ENDPOINT}"
    tls:
      insecure: true
  zipkin:
    endpoint: "${ZIPKIN_ENDPOINT}"
    tls:
      insecure: true
  otlp/aspecto:
      endpoint: "${ASPECTO_ENDPOINT}"
      headers:
        Authorization: "${ASPECTO_APIKEY}"
  azuremonitor:
    instrumentation_key: "${AZ_INSTRUMENTATION_KEY}"
  datadog:
    api:
      key: "${DATADOG_KEY}"
      site: "${DATADOG_SITE}"
        
service:
  pipelines:
    traces:
      receivers:
        - otlp
        - zipkin
      processors: [batch]
      exporters:
        - logging 
        - file/traces
        - otlp
        - zipkin
        - otlp/aspecto
        - azuremonitor
    metrics:
      receivers:
        - otlp
        - hostmetrics
      processors: [batch]
      exporters:
        - logging 
        - file/metrics
        - prometheus
        - datadog
    logs:
      receivers:
        - otlp
      processors: [batch]
      exporters:
        - logging 
        - file/logs
        - loki
        - azuremonitor
        - datadog
  extensions:
    - health_check
    - zpages